import "./globals.css";
import type { Metadata } from "next";
import { Sora } from "next/font/google";
import { NextAuthProvider } from "@/app/api/auth/Providers";
import Navbar from "./components/Navbar";

const inter = Sora({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider><Navbar />{children}</NextAuthProvider>
      </body>
    </html>
  );
}
